id = 0
[router]
max_connections = 9999
max_outgoing_packet_count = 500
max_segment_size = 104857600
max_segment_count = 50

[v4.1]
name = "monqtt-v4-1"
listen = "0.0.0.0:1883"
next_connection_delay_ms = 1
    [v4.1.connections]
    connection_timeout_ms = 60000
    max_payload_size = 20480
    max_inflight_count = 100
    dynamic_filters = true
 #   auth = { user1 = "p@ssw0rd", user2 = "password" }
 #      [v4.1.connections.auth]
 #      user1 = "p@ssw0rd"
 #      user2 = "password"
 #
 [v4.2]
 name = "monqtt-v4-2"
 listen = "0.0.0.0:1884"
 next_connection_delay_ms = 1
     # [v4.2.tls]
     # capath = "/etc/tls/ca.cert.pem"
     # certpath = "/etc/tls/server.cert.pem"
     # keypath = "/etc/tls/server.key.pem"
     [v4.2.connections]
     connection_timeout_ms = 60000
     throttle_delay_ms = 0
     max_payload_size = 20480
     max_inflight_count = 100
     max_inflight_size = 1024

[v5.1]
name = "monqtt-v5-1"
listen = "0.0.0.0:1885"
next_connection_delay_ms = 1
    [v5.1.connections]
    connection_timeout_ms = 60000
    max_payload_size = 20480
    max_inflight_count = 100

[console]
listen = "0.0.0.0:8085"
